In [1]:
!pip install mlxtend

Requirement already satisfied: mlxtend in c:\users\dai.studentsdc\appdata\local\anaconda3\lib\site-packages (0.23.3)
Requirement already satisfied: scipy>=1.2.1 in c:\users\dai.studentsdc\appdata\local\anaconda3\lib\site-packages (from mlxtend) (1.11.4)
Requirement already satisfied: numpy>=1.16.2 in c:\users\dai.studentsdc\appdata\local\anaconda3\lib\site-packages (from mlxtend) (1.26.4)
Requirement already satisfied: pandas>=0.24.2 in c:\users\dai.studentsdc\appdata\local\anaconda3\lib\site-packages (from mlxtend) (2.2.2)
Requirement already satisfied: scikit-learn>=1.3.1 in c:\users\dai.studentsdc\appdata\local\anaconda3\lib\site-packages (from mlxtend) (1.4.2)
Requirement already satisfied: matplotlib>=3.0.0 in c:\users\dai.studentsdc\appdata\local\anaconda3\lib\site-packages (from mlxtend) (3.9.2)
Requirement already satisfied: joblib>=0.13.2 in c:\users\dai.studentsdc\appdata\local\anaconda3\lib\site-packages (from mlxtend) (1.4.2)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\dai.studentsdc\appdata\local\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (1.2.0)
Requirement already satisfied: cycler>=0.10 in c:\users\dai.studentsdc\appdata\local\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\dai.studentsdc\appdata\local\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (4.51.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\dai.studentsdc\appdata\local\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (1.4.4)
Requirement already satisfied: packaging>=20.0 in c:\users\dai.studentsdc\appdata\local\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (23.2)
Requirement already satisfied: pillow>=8 in c:\users\dai.studentsdc\appdata\local\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (10.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\dai.studentsdc\appdata\local\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (3.0.9)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\dai.studentsdc\appdata\local\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\dai.studentsdc\appdata\local\anaconda3\lib\site-packages (from pandas>=0.24.2->mlxtend) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\dai.studentsdc\appdata\local\anaconda3\lib\site-packages (from pandas>=0.24.2->mlxtend) (2023.3)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\users\dai.studentsdc\appdata\local\anaconda3\lib\site-packages (from scikit-learn>=1.3.1->mlxtend) (2.2.0)
Requirement already satisfied: six>=1.5 in c:\users\dai.studentsdc\appdata\local\anaconda3\lib\site-packages (from python-dateutil>=2.7->matplotlib>=3.0.0->mlxtend) (1.16.0)

In [2]:
import pandas as pd
from mlxtend.frequent_patterns import apriori, association_rules
import os
os.chdir(r"C:\Users\dai\Desktop\S-AI\MachineLearning\Day12\Datasets")

In [3]:
fp_df = pd.read_csv('Faceplate.csv',index_col=0)
fp_df = fp_df.astype(bool)
fp_df

               Red  White   Blue  Orange  Green  Yellow
Transaction
1             True   True  False   False   True   False
2            False   True  False    True  False   False
3            False   True   True   False  False   False
4             True   True  False    True  False   False
5             True  False   True   False  False   False
6            False   True   True   False  False   False
7             True  False   True   False  False   False
8             True   True   True   False   True   False
9             True   True   True   False  False   False
10           False  False  False   False  False    True

In [17]:
itemsets = apriori(fp_df, min_support=0.2, use_colnames=True)
itemsets

    support             itemsets
0       0.6                (Red)
1       0.7              (White)
2       0.6               (Blue)
3       0.2             (Orange)
4       0.2              (Green)
5       0.4         (White, Red)
6       0.4          (Blue, Red)
7       0.2         (Green, Red)
8       0.4        (Blue, White)
9       0.2      (White, Orange)
10      0.2       (Green, White)
11      0.2   (Blue, White, Red)
12      0.2  (Green, White, Red)

In [19]:
# itemsets = apriori(fp_df, min_support=0.2, use_colnames=False)
# itemsets

In [21]:
# itemsets = apriori(fp_df, min_support=0.5, use_colnames=True)
# itemsets

In [44]:
rules = association_rules(df =itemsets, num_itemsets=len(fp_df), metric='lift',
                          min_threshold=1,return_metrics=['support','confidence','lift'])
rules.sort_values('confidence',ascending = False)

       antecedents     consequents  support  confidence      lift
2          (Green)           (Red)      0.2    1.000000  1.666667
5         (Orange)         (White)      0.2    1.000000  1.428571
6          (Green)         (White)      0.2    1.000000  1.428571
8   (Green, White)           (Red)      0.2    1.000000  1.666667
9     (Green, Red)         (White)      0.2    1.000000  1.428571
11         (Green)    (White, Red)      0.2    1.000000  2.500000
0           (Blue)           (Red)      0.4    0.666667  1.111111
1            (Red)          (Blue)      0.4    0.666667  1.111111
10    (White, Red)         (Green)      0.2    0.500000  2.500000
3            (Red)         (Green)      0.2    0.333333  1.666667
13           (Red)  (Green, White)      0.2    0.333333  1.666667
4          (White)        (Orange)      0.2    0.285714  1.428571
7          (White)         (Green)      0.2    0.285714  1.428571
12         (White)    (Green, Red)      0.2    0.285714  1.428571

## Cosmetics

In [51]:
cosmetics = pd.read_csv('Cosmetics.csv',index_col =0)
cosmetics.head()

,Bag,Blush,Nail Polish,Brushes,Concealer,Eyebrow Pencils,Bronzer,Lip liner,Mascara,Eye shadow,Foundation,Lip Gloss,Lipstick,Eyeliner
Trans.,,,,,,,,,,,,,,
1,0,1,1,1,1,0,1,1,1,0,0,0,0,1
2,0,0,1,0,1,0,1,1,0,0,1,1,0,0
3,0,1,0,0,1,1,1,1,1,1,1,1,1,0
4,0,0,1,1,1,0,1,0,0,0,1,0,0,1
5,0,1,0,0,1,0,1,1,1,1,0,1,1,0

In [53]:
fp_cos = cosmetics.astype(bool)

In [55]:
fp_cos

,Bag,Blush,Nail Polish,Brushes,Concealer,Eyebrow Pencils,Bronzer,Lip liner,Mascara,Eye shadow,Foundation,Lip Gloss,Lipstick,Eyeliner
Trans.,,,,,,,,,,,,,,
1,False,True,True,True,True,False,True,True,True,False,False,False,False,True
2,False,False,True,False,True,False,True,True,False,False,True,True,False,False
3,False,True,False,False,True,True,True,True,True,True,True,True,True,False
4,False,False,True,True,True,False,True,False,False,False,True,False,False,True
5,False,True,False,False,True,False,True,True,True,True,False,True,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
996,False,False,False,False,False,False,False,False,False,False,False,False,False,False
997,False,False,False,False,False,False,False,False,False,False,True,True,False,False
998,False,True,True,True,True,False,False,True,False,False,True,False,True,True
999,True,True,False,False,True,False,False,False,True,True,False,False,True,True
1000,False,False,False,False,True,False,True,True,False,True,False,False,False,True

In [69]:
itemsets1 = apriori(fp_cos, min_support=0.2, use_colnames=True)
itemsets1

    support                  itemsets
0     0.363                   (Blush)
1     0.280             (Nail Polish)
2     0.442               (Concealer)
3     0.279                 (Bronzer)
4     0.234               (Lip liner)
5     0.357                 (Mascara)
6     0.381              (Eye shadow)
7     0.536              (Foundation)
8     0.490               (Lip Gloss)
9     0.322                (Lipstick)
10    0.457                (Eyeliner)
11    0.220        (Blush, Concealer)
12    0.204      (Mascara, Concealer)
13    0.201   (Concealer, Eye shadow)
14    0.231   (Concealer, Foundation)
15    0.218    (Lip Gloss, Concealer)
16    0.297     (Eyeliner, Concealer)
17    0.321     (Mascara, Eye shadow)
18    0.211  (Eye shadow, Foundation)
19    0.201   (Lip Gloss, Eye shadow)
20    0.356   (Lip Gloss, Foundation)
21    0.238    (Eyeliner, Foundation)
22    0.227     (Lip Gloss, Eyeliner)

In [71]:
rules1 = association_rules(df =itemsets1, num_itemsets=len(fp_cos), metric='lift',
                          min_threshold=1,return_metrics=['support','confidence','lift'])
rules1.sort_values('confidence',ascending = False)

     antecedents   consequents  support  confidence      lift
10     (Mascara)  (Eye shadow)    0.321    0.899160  2.359999
11  (Eye shadow)     (Mascara)    0.321    0.842520  2.359999
16   (Lip Gloss)  (Foundation)    0.356    0.726531  1.355468
9    (Concealer)    (Eyeliner)    0.297    0.671946  1.470341
17  (Foundation)   (Lip Gloss)    0.356    0.664179  1.355468
8     (Eyeliner)   (Concealer)    0.297    0.649891  1.470341
0        (Blush)   (Concealer)    0.220    0.606061  1.371178
2      (Mascara)   (Concealer)    0.204    0.571429  1.292825
12  (Eye shadow)  (Foundation)    0.211    0.553806  1.033220
5   (Eye shadow)   (Concealer)    0.201    0.527559  1.193573
15  (Eye shadow)   (Lip Gloss)    0.201    0.527559  1.076651
1    (Concealer)       (Blush)    0.220    0.497738  1.371178
19    (Eyeliner)   (Lip Gloss)    0.227    0.496718  1.013710
7    (Concealer)   (Lip Gloss)    0.218    0.493213  1.006556
18   (Lip Gloss)    (Eyeliner)    0.227    0.463265  1.013710
3    (Concealer)     (Mascara)    0.204    0.461538  1.292825
4    (Concealer)  (Eye shadow)    0.201    0.454751  1.193573
6    (Lip Gloss)   (Concealer)    0.218    0.444898  1.006556
14   (Lip Gloss)  (Eye shadow)    0.201    0.410204  1.076651
13  (Foundation)  (Eye shadow)    0.211    0.393657  1.033220